###

# get all posts
GET http://localhost:8080/posts

###

# get posts by sender
GET http://localhost:8080/posts?sender=Kevin

###

# create post
POST http://localhost:8080/posts 
Content-Type: application/json

{
"title": "Hello", "sender": "Kevin", "content": "Hello World..."
}

###

# get post by id
GET http://localhost:8080/posts/673b418c7a4c7c28093f2633

###

# update post
PUT http://localhost:8080/posts/673b418c7a4c7c28093f2633
Content-Type: application/json

{
"title": "HelloOOOOOOOOOO", "sender": "GUY ATTIAS", "content": "GUY IS THE KING"
}

###

# delete comment
DELETE  http://localhost:8080/comments/673ca8547843cfb55725c80f

###

# get comments by post
GET   http://localhost:8080/comments/post/673b418c7a4c7c28093f2633

###

# create comment
POST http://localhost:8080/comments 
Content-Type: application/json

{
"postID": "673b418c7a4c7c28093f2633", "sender": "Kevin", "content": "Hello World..."
}

###

# update comment
PUT http://localhost:8080/comments/674067d4a1718b4a54d307b8
Content-Type: application/json

{
 "sender": "IDO", "content": "IDO IS THE GOAT"
}

###

# get comment by id
GET   http://localhost:8080/comments/674069829f3ed9c93edb75b0

###

# update user
PUT http://localhost:8080/users/67796f764899e36c4973095c
Content-Type: application/json

{
 "username": "ido4"
}

###

# delete user
DELETE http://localhost:8080/users/677ae1f6b98980457edaa579

###

# get user by id
GET http://localhost:8080/users/67796f764899e36c4973095c

###

# get all users
GET http://localhost:8080/users

###

# register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "ido", "password": "123456", "email": "ido@gmail.com", "birthDate": "2002-10-26"
}

###

# login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "ido", "password": "123456"
}

###

# logout
POST http://localhost:8080/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdjMWY5YzMzMGU4YzdiNTk5OWQzNzAiLCJpYXQiOjE3MzYxOTE4ODEsImV4cCI6MTczNjI3ODI4MX0.RvL65B0TtouRbN6unAMmI2lAEmwQGtqAegxWcbFRz98"
}

###

# refresh
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdjMWY5YzMzMGU4YzdiNTk5OWQzNzAiLCJpYXQiOjE3MzYxOTE4NTcsImV4cCI6MTczNjI3ODI1N30.olJdjzUTKepAauVx8sNKeeDQPaU9B6E9xE7m4uzzYpI"
}

###